# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='url',
            field=models.CharField(default='http://google.com', max_length=500),
            preserve_default=False,
        ),
    ]
