# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_link_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AddField(
            model_name='link',
            name='url_type',
            field=models.CharField(default='internship', max_length=20),
            preserve_default=False,
        ),
    ]
