# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_applicationstatus_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstatus',
            name='student_type',
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='status',
            field=models.IntegerField(choices=[(0, 'deadline passed'), (1, 'followup'), (2, 'successful'), (3, 'interviewing'), (4, 'post interview'), (5, 'rejected'), (6, 'todo'), (7, 'waiting')], default=6),
        ),
    ]
