# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0005_auto_20160907_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url_type',
            field=models.IntegerField(choices=[(0, 'internship'), (1, 'full time')], default=0),
        ),
    ]
