# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0006_auto_20160907_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationstatus',
            options={'verbose_name_plural': 'application statuses'},
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='notes',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='link',
            name='url_type',
            field=models.IntegerField(choices=[(0, 'internship'), (1, 'full time')], default=1),
        ),
    ]
