# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0007_auto_20160912_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='application_status',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.IntegerField(choices=[(0, 'deadline passed'), (1, 'followup'), (2, 'successful'), (3, 'interviewing'), (4, 'post interview'), (5, 'rejected'), (6, 'todo'), (7, 'waiting')], default=6),
        ),
        migrations.DeleteModel(
            name='ApplicationStatus',
        ),
    ]
